### ISSUE TITLE
ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request

### ISSUE THREAD

**Issue by haoziyeung** [PapenfussLab/PathOS#4]
hello,now i'm using pathOS,
i login with Pathos Admin,then i navigate to http://192.168.0.39:8082/PathOS/seqVariant/svlist/170228_M01053_0504_000000000-B38HY/NA12878-1
,then EDIT chr20:g.31024359T>C ,and save to report ,then i'm clicking "Draft Sample Analysis(PDF)",sometimes i can get a pdf report in a new tab ,but sometimes theres alot of error in console.like below:
pathos-tomcat_1   | 2017-05-15 12:44:12,441 [http-apr-8080-exec-6] WARN  easygrid.EasygridDispatchService  - No service method for: callGridImplHtmlGridDefinition
pathos-tomcat_1   | 2017-05-15 12:44:16,975 [http-apr-8080-exec-9] WARN  curate.ReportService  - Template file doesn't exist: /pathology/NGS/pa_local/Report/MP FLD Myeloid Production Var Template.docx
pathos-tomcat_1   | 2017-05-15 12:44:16,986 [http-apr-8080-exec-9] ERROR curate.ReportRenderService  - Aspose license file doesn't exist /pathology/NGS/pa_local/Report/License/Aspose.Total.Java.lic
pathos-tomcat_1   | 2017-05-15 12:44:16,986 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Generating report for sample NA12878-1 from /pathology/NGS/pa_local/Report/Default Var Template.docx into /usr/local/tomcat/work/Catalina/localhost/PathOS/Report_NA12878-1.pdf
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableStart:Samples
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: sample
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableEnd:Samples
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableStart:Samples
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: patient
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: urn
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: dob
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: sex
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: location
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: requester
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: sample
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: extref
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: collect_date
pathos-tomcat_1   | 2017-05-15 12:44:17,082 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: rcvd_date
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: isdraft
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableStart:Variants
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: gene
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: refseq
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: hgvsc
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: hgvsp
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: varreaddepth
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: totalreaddepth
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: afpct
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: class
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableEnd:Variants
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableStart:Variants
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: gene
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: mut
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableEnd:Variants
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: ampReads
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: ampPct
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableStart:Variants
pathos-tomcat_1   | 2017-05-15 12:44:17,083 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: genedesc
pathos-tomcat_1   | 2017-05-15 12:44:17,084 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableEnd:Variants
pathos-tomcat_1   | 2017-05-15 12:44:17,084 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: lowAmps
pathos-tomcat_1   | 2017-05-15 12:44:17,084 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: rois
pathos-tomcat_1   | 2017-05-15 12:44:17,084 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableStart:Variants
pathos-tomcat_1   | 2017-05-15 12:44:17,084 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: refs
pathos-tomcat_1   | 2017-05-15 12:44:17,084 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableEnd:Variants
pathos-tomcat_1   | 2017-05-15 12:44:17,084 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Merge field: TableEnd:Samples
pathos-tomcat_1   | 2017-05-15 12:44:17,114 [http-apr-8080-exec-9] INFO  curate.ReportRenderService  - Variant: ASXL1:c.3844T>C
pathos-tomcat_1   | 2017-05-15 12:44:17,122 [http-apr-8080-exec-9] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /PathOS/seqVariant/reportPdf/62946
pathos-tomcat_1   | Stacktrace follows:
pathos-tomcat_1   | java.lang.NullPointerException
pathos-tomcat_1   |     at org.petermac.pathos.curate.ReportRenderService.getVariantMaps(ReportRenderService.groovy:352)
pathos-tomcat_1   |     at org.petermac.pathos.curate.ReportRenderService.createVariantTable(ReportRenderService.groovy:223)
pathos-tomcat_1   |     at org.petermac.pathos.curate.ReportRenderService.getDataSet(ReportRenderService.groovy:167)
pathos-tomcat_1   |     at org.petermac.pathos.curate.ReportRenderService.mergeSampleDocument(ReportRenderService.groovy:128)
pathos-tomcat_1   |     at org.petermac.pathos.curate.ReportRenderService.runReport(ReportRenderService.groovy:67)
pathos-tomcat_1   |     at org.petermac.pathos.curate.ReportService.sampleReport(ReportService.groovy:72)
pathos-tomcat_1   |     at org.petermac.pathos.curate.SeqVariantController.reportPdf(SeqVariantController.groovy:261)
pathos-tomcat_1   |     at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:200)
pathos-tomcat_1   |     at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
pathos-tomcat_1   |     at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
pathos-tomcat_1   |     at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
pathos-tomcat_1   |     at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
pathos-tomcat_1   |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
pathos-tomcat_1   |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
pathos-tomcat_1   |     at java.lang.Thread.run(Thread.java:745)

and there's no PDF report,otherwise a "An error has occurred" on a new page.
Do I make myself clear?

**Comment by kendoig** [comment]
I can see whats going on, I suspect the database is not consistent with some curated variants.
I've fixed the NullPointer bug but I suspect this is not the root cause.
Can you rebuild and retry

**Comment by haoziyeung** [comment]
fine,i'll try.thanks
